<form class="form-horizontal" role="form" method="post" action="/login" autocomplete="off">
    <input type="text" style="display:none" />
    <div class="form-group">
        <label for="sl-login1" class="col-sm-2 control-label"><?= _('Логин') ?></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="sl-login1" name="form-login[login]" placeholder="Login">
        </div>
    </div>
    <div class="form-group">
        <label for="sl-password1" class="col-sm-2 control-label"><?= _('Пароль') ?></label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="sl-password1" name="form-login[password]" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="form-login[remember_me]">&nbsp;<?= _('Запомнить меня') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default"><?= _('Войти') ?></button>
        </div>
    </div>
</form>
