<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" />
    <title><?= $this->title ?></title>
    <link href="/plugins/bootstrap-3.3.0/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="" type="image/x-icon">
    <link rel="icon" href="">

</head>

<body>
<div class="wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <?= $this->menu; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <article class="tablelist">
                    <div class="article-container">
                        <div class="row spc-panel-info">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="alert alert-success hidden" role="alert" data-description="<?= _('Сообщение') ?>"></div>
                                <div class="alert alert-danger hidden" role="alert" data-description="<?= _('Ошибка') ?>"></div>
                            </div>
                        </div>
                        <?= $this->content; ?>
                    </div>
                </article>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <footer class="text-center">
                    <?= $this->footer; ?>
                </footer>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade spc-warning-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <a href="#" class="spc-warning-modal-link"><button type="button" class="btn btn-danger"><?= _('Продолжить') ?></button></a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><?= _('Отмена') ?></button>
            </div>
        </div>
    </div>
</div>

<div class="spc-loader-wrapper spc-dontshow">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title"><?= _('Пожалуйста, подождите') ?>...</h4>
            </div>
            <div class="modal-body">
                <div class="progress progress-striped active">
                    <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->

<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="/plugins/bootstrap-3.3.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/spc/form.js"></script>
<script type="text/javascript" src="/js/spc/layout.js"></script>
<script type="text/javascript" src="/js/spc/loader.js"></script>

</body>
</html>
