<?php
    $route = $this->app['route'];
?>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">SPC</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="<?= $route == '/main' ? 'active' : '' ?>"><a href="/main"><?= _('Главная') ?></a></li>
                <li class="<?= $route == '/order/example' ? 'active' : '' ?>"><a href="/order/example"><?= _('Страничка') ?></a></li>
                <li class="<?= $route == '/order/example2' ? 'active' : '' ?>"><a href="/order/example2"><?= _('Пример') ?></a></li>
                <li class="<?= $route == '/other' ? 'active' : '' ?>"><a href="/other"><?= _('Что-то ещё') ?></a></li>
                <li class="<?= $route == '/other2' ? 'active' : '' ?>"><a href="/other2"><?= _('Будет 404') ?></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><div class="glyphicon glyphicon-user"></div>&nbsp;<?= $this->user_name ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#"><?= _('Профиль') ?></a></li>
                        <li class="divider"></li>
                        <li><a class="spc-warning-link" data-message="<?= _('Выйти из системы') ?>" data-description="<?= _('Вы уверены что хоите выйти?') ?>" href="/logout"><?= _('Выйти') ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>